"""Shareable Markdown report."""

from __future__ import annotations

from collections.abc import Callable

from cuda_doctor.core.enums import Severity
from cuda_doctor.core.models import EnvironmentSnapshot
from cuda_doctor.diagnosis.engine import DiagnosisResult
from cuda_doctor.diagnosis.issue import Issue
from cuda_doctor.reporters.base import Reporter, ReportInputs, format_memory
from cuda_doctor.utils.redact import redact_text
from cuda_doctor.version import __version__

_SEVERITY_LABEL = {
    Severity.CRITICAL: "🔴 CRITICAL",
    Severity.ERROR: "🔴 ERROR",
    Severity.WARNING: "🟡 WARNING",
    Severity.INFO: "🔵 INFO",
}


class MarkdownReporter(Reporter):
    """Report formatted for GitHub issues, PRs, and documentation."""

    def render(self, inputs: ReportInputs) -> str:
        snapshot, result = inputs.snapshot, inputs.result
        lines: list[str] = []
        add = lines.append

        add("# CUDA Doctor Report")
        add("")
        add(
            f"Generated by cuda-doctor v{__version__} at {inputs.generated_at}"
            f" (target: {snapshot.system.platform.value})."
        )
        add("")

        self._environment_overview(snapshot, add)
        self._issues(result, add)
        self._summary(result, add)
        return "\n".join(lines).rstrip() + "\n"

    # -- sections -----------------------------------------------------------

    def _environment_overview(
        self, snapshot: EnvironmentSnapshot, add: Callable[[str], None]
    ) -> None:
        add("## Environment Overview")
        add("")
        system = snapshot.system
        add(
            f"- **OS**: {system.os_name} {system.os_version}"
            f" (kernel {system.kernel_version}, {system.architecture})"
        )
        add(f"- **Python**: {system.python_version} ({redact_text(system.python_executable)})")

        if snapshot.gpus:
            names = {gpu.name for gpu in snapshot.gpus}
            if len(names) == 1:
                gpu = snapshot.gpus[0]
                memory = format_memory(gpu.memory_total_mb)
                each = f" ({memory} each)" if memory else ""
                add(f"- **GPU(s)**: {len(snapshot.gpus)} x {gpu.name}{each}")
            else:
                devices = ", ".join(
                    f"{gpu.name} {format_memory(gpu.memory_total_mb)}".rstrip()
                    for gpu in snapshot.gpus
                )
                add(f"- **GPU(s)**: {devices}")
        else:
            add("- **GPU(s)**: none detected")

        driver = snapshot.driver
        if driver and driver.version:
            max_cuda = f" (max CUDA {driver.cuda_version})" if driver.cuda_version else ""
            add(f"- **NVIDIA driver**: {driver.version}{max_cuda}")

        cuda = snapshot.cuda
        if cuda.nvcc_found and cuda.nvcc_path:
            version = f" (CUDA {cuda.toolkit_version})" if cuda.toolkit_version else ""
            add(f"- **CUDA Toolkit**: {redact_text(cuda.nvcc_path)}{version}")
        else:
            add("- **CUDA Toolkit**: nvcc not found on PATH")
        if cuda.installations:
            listing = ", ".join(
                f"CUDA {install.version or '?'} ({redact_text(install.path)})"
                for install in cuda.installations
            )
            add(f"- **Toolkit installations**: {listing}")

        torch_info = snapshot.pytorch
        if not torch_info.installed:
            add("- **PyTorch**: not installed")
        elif torch_info.import_error:
            add("- **PyTorch**: installed but cannot be imported")
        else:
            build = f"CUDA {torch_info.cuda_version}" if torch_info.is_cuda_build else "CPU-only"
            available = "available" if torch_info.cuda_available else "**not available**"
            add(f"- **PyTorch**: {torch_info.version} ({build} build, CUDA {available})")

        compilers = [tool for tool in snapshot.compiler.compilers if tool.found]
        if compilers:
            chain = ", ".join(
                f"{tool.name} {tool.version or '?'}" for tool in compilers
            )
            add(f"- **C++ toolchain**: {chain}")
        add("")

    def _issues(self, result: DiagnosisResult, add: Callable[[str], None]) -> None:
        add("## Potential Issues")
        add("")
        if not result.issues:
            add("No issues found. ✅")
            add("")
            return
        for issue in result.issues:
            self._issue(issue, add)

    def _issue(self, issue: Issue, add: Callable[[str], None]) -> None:
        add(f"### {_SEVERITY_LABEL[issue.severity]} · `{issue.code}` — {issue.title}")
        add("")
        if issue.description:
            add(issue.description)
            add("")
        if issue.evidence:
            add("**Evidence**")
            add("")
            for line in issue.evidence:
                add(f"- `{redact_text(line)}`")
            add("")
        if issue.recommendations:
            add("**Recommendations**")
            add("")
            for line in issue.recommendations:
                add(f"- {redact_text(line)}")
            add("")

    def _summary(self, result: DiagnosisResult, add: Callable[[str], None]) -> None:
        summary = result.summary
        add("## Summary")
        add("")
        add(f"**Status: {summary.status.value}**")
        add("")
        add(
            f"{summary.critical} critical · {summary.errors} errors · "
            f"{summary.warnings} warnings · {summary.info} info"
        )
        add("")
